# .github/workflows/chromatic.yml

name: "Chromatic"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Use Specific Yarn Version
        run: corepack prepare yarn@4.1.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
